spring:
  #激活哪一个环境的配置文件
  profiles: dev
  #连接池配置
  datasource:
    # 数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/mhwfy_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&allowMultiQueries=true
    username: root
    password: root

#日志
logging:
  config: classpath:log/logback.xml
  path: log/seed
  level:
       cn.ulegal.mapper: debug
